.github/workflows/ci.yml, .github/workflows/publish.yml, .github/workflows/tag_and_release.yml, CHANGELOG.rst, DEVELOPMENT.rst, tag-from-pipeline.sh
A github workflow to automatically tag and create a new release when when changelog is updated in a pull request.
1. on pull request (before and after merge) check that the new tag is valid and does not collide with another one.
2. on pull request (only after merge) create the new tag and the release.
COMP-212
=> Automatic tag and release on master merge

.github/workflows/publish.yml, .github/workflows/tag_and_release.yml
When the publish workflow is triggered from another workflow it will fail unless necessary secrets as passed to it from the caller workflow. This PR adds these secrets to the workflow call.
COMP-212
=> Pass secrets to the workflow call

CHANGELOG.rst, src/iqm_client/iqm_client.py, tests/test_iqm_client.py
When the IQM server response contains warnings, those are emitted as python UserWarning
=> Emit warnings in response as python UserWarning

.github/workflows/publish.yml
In order to get clean release number, the docs must be built on a tagged commit.
Add checkout step to `publish_docs` job to get to the last tagged commit.
Tags are available only if `actions/checkout@v2` fetches the full history.
For that to happen it needs parameter `fetch-depth: 0`.
=> Checkout last tagged commit in publish workflow

.github/workflows/publish.yml
Selecting latest tag with `git tag -l | tail -1` will not work when release number grows to double-digits because `git tag` lists tags in alphabetical order. Use `git describe --tags --abbrev=0` instead to get the latest tag in current branch.
=> Use git describe to get the latest tag in publish workflow

CHANGELOG.rst, src/iqm_client/iqm_client.py, tests/test_iqm_client.py
The validation (starting with http, https) is expected by the docstring but not enforced.
It might be helpful to fail early and fast since there might be some prior resource intensive steps before utilising the IQM client.
=> Added url validation for starting with http, https

CHANGELOG.rst, src/iqm_client/iqm_client.py, tests/conftest.py, tests/test_iqm_client.py
If submitted circuit uses physical qubit names directly there is no need for name mapping and qubit_mapping can be omitted.
=> Make qubit_mapping an optional parameter in submit_circuit

AUTHORS.rst, CHANGELOG.rst, src/iqm_client/iqm_client.py, tests/conftest.py, tests/test_iqm_client.py
A new feature of IQM server allows to check the status of a job at a new endpoint `/jobs/$jobId/status`. Unlike previously existing endpoint `/jobs/$jobId`, the new endpoint will not return measurement results in case the job is finished.
=> Add function to check job status

.github/workflows/ci.yml, .github/workflows/publish.yml
Change github actions so that full git history (including tags) is checked out when building docs. This is needed for multiversion docs, which are built separately for each git tag.
=> Checkout full history when building docs

tests/conftest.py
The structure for the test case does not reflect the documentation at the moment. This pull request changes it, so it uses the same structure as the demo.
=> Update args structure for phased rx test case

CHANGELOG.rst, docs/generate_json_schemas.py, src/iqm_client/iqm_client.py, tests/conftest.py, tests/test_generate_run_request_json_schema.py, tests/test_iqm_client.py
Allow users to provide a `calibration_set_id`. Calibration data will be retrieved from the observations database by IQM Server. If `calibration_set_id` is provided, `settings` should not be provided, and vice versa (IQM Server, namely CoCoS, will reject any requests containing both fields simultaneously).
=> Add optional calibration_set_id to the request sent to IQM Server

CHANGELOG.rst, src/iqm_client/iqm_client.py, tests/test_authentication.py
New external token is now obtained from tokens file if old token is about to expire.
=> Fix errors caused by expired external token

.mypy.ini, CHANGELOG.rst, src/iqm_client/iqm_client.py
The idea is IQM Client does not depend on OpenTelemetry, but if there is an active context (e.g. someone is profiling circuits execution time), it will add necessary headers to the backend request. Mostly used internally by IQM.
=> OpenTelemetry support

CHANGELOG.rst, src/iqm_client/iqm_client.py
IQM Server might be busy and unable to accept new connections. This is a temporary workaround until the server is actually fixed.
=> Keep retrying connecting to the IQM Server on 502 error

CHANGELOG.rst, src/iqm_client/iqm_client.py
And reduce default value to 1 sec (as error 502 has another workaround for now).
=> Make IQM Server requests interval configurable

CHANGELOG.rst, src/iqm_client/iqm_client.py, tests/conftest.py, tests/test_authentication.py
Fetching the quantum architecture is the first step in e.g. `iqm-qiskit` and should provide a meaningful error message is the auth credentials are missing.
=> Check if auth is missing on quantum architecture fetch

.github/workflows/publish.yml, CHANGELOG.rst, docs/conf.py, setup.cfg, tox.ini, tox_docs_helper.py
Configure Tox to skip rebuilding documentation for the versions that already exist.
Implementation uses a Python helper file to check out available versions of documentation from Git branch. The helper file is OS agnostic
=> COMP-584 Improve multiversion documentation

CHANGELOG.rst, INTEGRATION_GUIDE.rst, setup.cfg, src/iqm_client/util.py, tests/test_util.py
The function can be used to sanitise data (e.g. circuit metadata) before sending it IQMClient.
=> Add utility function `to_json_dict`

.pylintrc, CHANGELOG.rst, setup.cfg, src/iqm_client/iqm_client.py, src/iqm_client/models.py, tests/conftest.py, tests/test_iqm_client.py
Implement circuit validation using custom validators in Pydantic models
=> COMP-781: Validate input arguments

CHANGELOG.rst, src/iqm/iqm_client/iqm_client.py, tests/conftest.py, tests/test_iqm_client.py
Previously, `wait_for_results()` and `wait_for_compilation()` used `get_run()` to check the status of the job. The RunResult returned by `get_jobs()` contains metadata which contains the original job request, so if the original job request was large, it could take a long time to send and decode the RunResult JSON even before job results are ready. This meant that, for example, `wait_for_results()` might end up checking the status only every 30 seconds (because of the RunResult overhead) while it was supposed to check the status once every second. With unlucky timing, this could then lead to a situation where the job has already finished on the server, but `wait_for_results()` returns `APITimeoutError` long after that.
This MR fixes the problem by using `get_run_status()` instead of …
=> Use get_run_status() instead of get_run() to check status

CHANGELOG.rst, src/iqm/iqm_client/iqm_client.py, tests/conftest.py, tests/test_iqm_client.py
Changing `@field_validator('instructions', mode='before')` to use default `mode` value of `after` allows pydantic to parse incoming dictionaries and create `Instruction` objects.
=> leverage pydantic parsing instructions

CHANGELOG.rst, INTEGRATION_GUIDE.rst, src/iqm/iqm_client/iqm_client.py, tests/conftest.py
=> Remove circuit_duration_check from RunRequest, add max_circuit_duration_over_t2

.github/workflows/publish.yml, .github/workflows/tag_and_release.yml, CHANGELOG.rst, tox.ini
- Separate ```push_to_pypi``` job into two jobs: ```build``` and ```push_to_pypi```
- Use ```publish``` workflow file from current feature branch rather than ```main``` branch
- Do not use ```tox``` in ```publish``` workflow to build and upload package
- Remove ```twine``` dependency
- Remove ```publish``` configuration from ```tox```
- Remove references to PyPI secrets
=> Use GitHub Action Trusted Publisher for PyPI publishing

README.rst
This is needed for PyPI publishing
=> Remove :file: anchor from README

CHANGELOG.rst, INTEGRATION_GUIDE.rst, src/iqm/iqm_client/iqm_client.py, tests/test_iqm_client.py
Extracts the creation and submission of run request from `submit_circuits()` into separate functions. This allows inspecting a run request programmatically, before/without actually submitting it for execution. From user's perspective, there is no change to `submit_circuits()` so this is not a breaking change. Also adds `IQM_CLIENT_DEBUG` environment variable for printing a run request when it is actually submitted.
=> Allow inspecting a RunRequest without submitting it for execution

.github/workflows/publish.yml, CHANGELOG.rst, DEVELOPMENT.rst, README.rst
Removes the files under `build/sphinx/html/.doctrees` when publishing the documentation to `gh-pages`. This helps reduce repository size growth, which was mainly due to the 4 MB `environment.pickle` file stored there.
Also updates documentation to suggest some `git clone` options which allow faster cloning by not including the full commit history.
**Testing**
I tested this on my personal `iqm-client` fork, you can see that the commit https://github.com/jkotilahti/iqm-client/commit/80a98e28fcdaade1bd8a2bd55e0ac2b077cc3e82 which does the modification to `publish.yml` results in `gh-pages` commit https://github.com/jkotilahti/iqm-client/commit/00f0d2001514181f349f847d75903aa124900612 which removes all files in `build/sphinx/html/.doctrees` from `gh-pages`. You can also check that any earlier …
=> Remove unnecessary build files when publishing documentation

CHANGELOG.rst, src/iqm/iqm_client/authentication.py, tests/test_authentication.py
External token can be any kind of token, not necessary JWT, like, for example IQM Resonance token. No need to verify it's expiration as its lifecycle is managed externally.
=> Do not check external token expiration.

CHANGELOG.rst, INTEGRATION_GUIDE.rst, docs/conf.py, src/iqm/iqm_client/errors.py, src/iqm/iqm_client/iqm_client.py, src/iqm/iqm_client/models.py, src/iqm/iqm_client/transpile.py, tests/conftest.py, tests/test_iqm_client.py, tests/test_transpiler.py, tests/test_validation.py, tox.ini
COMP-1491
- Bugfix: `CircuitCompilationOptions` that turn off MOVE validation were not used in local circuit validation. Improved testing to catch this situation
- Bugfix: MOVE gate validation works with a QPU with more than one resonator.
- Added a note in the changelog marking the CoCoS version that supports the `CircuitCompilationOptions` intruduced in `iqm-client==18.0`, older versions don't raise an error but the option is not supported and will be ignored.
- Docs updated.
- Validate that measurement keys in a circuit are unique.
- Added  `isort` into the tox formatting environment.
=> Bugfixes, better circuit validation, docs updated.

CHANGELOG.rst, src/iqm/iqm_client/iqm_client.py, tests/test_validation.py
Some `qiskit-on-iqm` unit tests fail without this fix.
=> Fix move gate validation for partial qubit mapping

CHANGELOG.rst, pyproject.toml, src/iqm/iqm_client/api.py, src/iqm/iqm_client/iqm_client.py, tests/conftest.py, tests/test_iqm_client.py
* The first commit adds a warning when initializing IQMClient connected to a server for which the reported compatible iqm-client version range (from `/info/client-libraries`) does not include the current version. The warning does not prevent using the client, since it is still possible that things work even if the version is officially incompatible. Example of how the warning looks like:
`UserWarning: Your IQM Client version 21.0 was built for a different version of IQM Server. You might encounter issues. For the best experience, consider using a version of IQM Client that satisfies 20.0 <= iqm-client < 21.0.`
* The second commit improves the error message when an endpoint returns 404 and the client version is incompatible with the server. This can happen if an endpoint used by the …
=> Add warnings when client version is not compatible with the server

CHANGELOG.rst, src/iqm/iqm_client/iqm_client.py, tests/test_iqm_client.py
In the previous PR https://github.com/iqm-finland/iqm-client/pull/145 a compatibility check expected dict key `iqm-client`, while actually `iqm_client` was returned from server, breaking client code.
This PR fixes the expected dict key and also ensures any other errors during compatibility check do not break the client completely.
=> Fixed client version compatibility check

CHANGELOG.rst, src/iqm/iqm_client/iqm_client.py, tests/test_iqm_client.py
The version compatibility check added in https://github.com/iqm-finland/iqm-client/pull/145 could in some cases raise an exception when initializing IQMClient, preventing usage of IQMClient. This should not happen, because the version check was only meant as an informative warning, never totally preventing usage. Some cases where this could happen were fixed in https://github.com/iqm-finland/iqm-client/pull/148, but there still remained the possibility that `versions_response = requests.get(...)` would raise an exception, leading to the same problem. 
This PR prevents the version check from ever raising exceptions, so that it never prevents the usage of IQMClient. Also some other small adjustments are made to the incompatibility messages and when they are returned.
=> Improve version compatibility check

CHANGELOG.rst, src/iqm/iqm_client/models.py, tox.ini
The repository was allowing warnings to be ignored by the sphinx while documents were generated. With this commit, we are now enforcing fail-on warnings. Current warnings are also fixed.
=> Fail document generation for sphinx warnings

CHANGELOG.rst, pyproject.toml
* Relax version range of numpy. https://github.com/iqm-finland/iqm-client/issues/164
* Relax version range of packaging, causes issues with other repos.
=> Less strict versions

CHANGELOG.rst, src/iqm/iqm_client/models.py, tests/test_iqm_client.py, tests/test_models.py
When Pydantic serializes a dict with tuple keys into JSON, the keys are turned into comma-separated strings (because JSON only supports string keys). That can happen for DQA if `GateInfo.override_default_implementation` has keys with multiple locus components. For example, `("QB2", "COMPR1")` key in Python becomes `"QB2,COMPR1"` in the JSON. But apparently Pydantic cannot automatically deserialize it back into the original format properly. 
This PR adds a [before field validator](https://docs.pydantic.dev/latest/concepts/validators/#field-validators) which converts such comma-separated strings back into tuples of strings. Also added a unit test which fails without this fix.
=> Fix DQA deserialization
